" Setting Fonts
set guifont=Monaco:h14

" Hidden left Scroll
set guioptions-=L
set guioptions-=r

" Setting Colorscheme
colorscheme desertEx

" Setting Current Work directory
autocmd BufEnter * silent! lcd %:p:h
