" Setting Fonts
set guifont=Monaco:h20

" Hidden left Scroll
set guioptions-=L
set guioptions-=r

" Setting Colorscheme
colorscheme flattown

" Setting Current Work directory
autocmd BufEnter * silent! lcd %:p:h

" Setting Transparency

set transparency=0
nnoremap <expr><F12> &transparency+40 >= 100 ? ":set transparency=0\<CR>" : ":let &transparency=&transparency+40\<CR>"
