alias ll='ls -l'
alias site='cd /Users/xi4oh4o/Sites'
#PS1='\[\033[01;32m\]\u@\h:\[\033[01;34m\]\w\]$ \[\033[00m\]'

# Setting PATH for Python 2.7
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}:$HOME/.pkg_uninstaller"
export PATH

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
